[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer_runs = 200
viaIR = true
evm_version = "shanghai"

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
base = "${BASE_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
